name: CD
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - uses: actions/checkout@v2

      - name: APT UPDATE and INSTALL SSHPASS
        run:
          sudo apt update && sudo apt install sshpass

      - name: deploy
        run:
          sshpass -e ssh -o stricthostkeychecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }}
          "cd /home/minecraft-servers/proxy/plugins/ && rm HardBack-1.1-SNAPSHOT.jar && wget https://github.com/HardBackFR/HardBackAPI/raw/main/target/HardBack-1.1-SNAPSHOT.jar"